### ISSUE TITLE
New assignments

### ISSUE THREAD

**Issue by glaville** [Archomeda/gw2-yolomouse-cursors#1]
Since the patch deployed about a month ago, the assignments included in the GIT repository no longer works ingame: the cursors indexes appears to have been updated.

Would it be possible to replace the old assignments with these new ones, which uses the new indexes?

Kind regards,
a fellow GW2 player

53=1613731120684182123,0
30=3879228045702550987,0
43=7403046177502690097,0
31=17048348893111081403,0
44=13490161824364967928,0
38=3378265761844623444,0
36=5786904908623985943,0
35=597863915932182310,0
42=14489599118870534192,0
32=1258658308601791288,0
48=6763233587493181264,0
47=11832488385584822342,0
41=5779025954529251451,0
40=15044639781277640853,0
37=17402700788602228968,0
30=13363729155134653096,0
46=3390773558136913462,0

**Comment by Archomeda** [comment]
Ah yes, thanks for reminding me. I already had them updated locally, but I completely forgot to actually put them here. YoloMouse has also included 10 more cursors by default in the 30-39 section between now and the last update.

I've been working on updating the cursors as well, but those aren't done yet. In the mean time, I'll update the repo to include these assignments, thanks!

**Comment by Archomeda** [comment]
They have been added, let me know if something is incorrect.

**Comment by glaville** [comment]
Example assigments working just fine, thank you! I just discovered the two new variants (circle and circle-hc) of cursors as well, very nice work 👍

**Comment by Archomeda** [comment]
Yep, those existed for a long time actually, just on a different branch because I was testing them first: 47fe3ae7d92f33f723ec7791b98fe9cc42e0f17f. I just forgot to merge it into the main branch afterwards.
